gcp bucket update
dapr/components-contrib pull request #1128
Opened 2021-09-08 14:50 UTC by fjvela

# Description

_Please explain the changes you've made_

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2021-09-17 04:36 UTC, yaron2 commented
@beiwei30 can you please review this?

2021-09-23 16:46 UTC, yaron2 commented
@fjvela please resolve the conflict and we'll move on to merging. thanks!

2021-09-27 10:08 UTC, beiwei30 requested changes
@fjvela Javier, your change looks good to me except for this minor issue.

2021-09-27 10:08 UTC, beiwei30 commented on bindings/gcp/bucket/bucket.go
> +		return nil, fmt.Errorf("s3 binding error. error merge metadata : %w", err)
Should this error msg be 'gcp binding error' instead of 's3‘?

2021-09-28 05:52 UTC, beiwei30 approved these changes
LGTM now, Thanks Javier for this effort.

2021-09-30 05:20 UTC, merged

2021-09-30 05:20 UTC, yaron2 commented
Merged. Thank you @fjvela for your contribution, and thank you @beiwei30 for the review.