CosmosDB Output Binding Stable Certification Tests
dapr/components-contrib pull request #1378
Opened 2021-12-14 00:42 UTC by berndverst

# Description

Certifications tests for the Cosmos DB Output Binding. With this PR merged the Output Binding can be considered Stable.

closes #958 

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2021-12-14 01:39 UTC, daixiang0 approved these changes

2021-12-15 04:57 UTC, artursouza requested changes

2021-12-15 09:15 UTC, berndverst commented on tests/certification/bindings/azure/cosmosdb/README.md
> -- TODO: Graceful handling of connection resets / interruption (client connection only, not during Invoke/Create operation itself)
Not applicable to the CosmosDB SQL API just like in KeyVault.

This is a REST client which maintains an authorization header. No connection is kept. There is nothing to interrupt.

2021-12-16 18:40 UTC, artursouza approved these changes

2021-12-16 18:41 UTC, merged