Fix kafka input binding looping when not topics are set
dapr/components-contrib pull request #1412
Opened 2022-01-06 10:34 UTC by Gehhilfe

Signed-off-by: Tim Burkert <burkert.tim@gmail.com>

# Description

Prevent kafka input binding reading when no topics are provided. When not or only malformed topics are provided, the read binding will loop forever and waste resources. 

![image](https://user-images.githubusercontent.com/448556/148369088-bcb567fe-475f-42fa-843f-819ffa8a7a16.png)

## Issue reference

Please reference the issue this PR will close: #1399 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2022-01-06 15:25 UTC, Taction commented
Thanks for your contribution! LGTM overall, just a small change.

2022-01-06 18:10 UTC, yaron2 commented
> Thanks for your contribution! LGTM overall, just a small change.

Did you submit your review? I don't see any comments.

2022-01-07 01:27 UTC, Taction requested changes

2022-01-07 01:32 UTC, Taction commented
> > Thanks for your contribution! LGTM overall, just a small change.
> 
> Did you submit your review? I don't see any comments.

Thanks, I have forgotten to submit it.

2022-01-07 07:19 UTC, Gehhilfe commented on bindings/kafka/kafka.go
> +		return errors.New("kafka error: no topics configured")
Done

2022-01-07 18:31 UTC, artursouza approved these changes

2022-01-07 19:03 UTC, mukundansundar approved these changes

2022-01-07 19:06 UTC, merged

2022-01-07 23:41 UTC, yaron2 commented
Thanks @Gehhilfe for this PR!