Added TTL to state store binding for DynamoDB
dapr/components-contrib pull request #1512
Opened 2022-02-19 10:16 UTC by wimvdc

# Description

Adding ttlInSeconds support to DynamoDB as state store.
Please see PR #1493 for discussion details

## Issue reference

#1489

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2022-02-19 11:09 UTC, wimvdc commented
See following PR for the documentation update.
https://github.com/dapr/docs/pull/2203

2022-02-21 20:18 UTC, yaron2 commented
@berndverst can you please re-review this PR?

2022-02-21 21:05 UTC, yaron2 commented
@wimvdc thanks for this PR, please see the failing lint (file needs to be `gofumpt`-ed).

2022-02-22 06:07 UTC, wimvdc commented
> @wimvdc thanks for this PR, please see the failing lint (file needs to be `gofumpt`-ed).

Thank you for your help and time on the Dapr projects.
I gofumpt-ed both files. 
Might be useful to add this step to some documentation/script (?)

2022-02-22 06:14 UTC, daixiang0 commented
> > @wimvdc thanks for this PR, please see the failing lint (file needs to be `gofumpt`-ed).
> 
> Thank you for your help and time on the Dapr projects. I gofumpt-ed both files. Might be useful to add this step to some documentation/script (?)

I think lint is common in all project, Go project usually use `golangci-lint` which include `gofumpt`. You can run `make lint` to detect lint issues, and you can get shell commands from CI logs in any project. Hope it helps.

2022-03-01 02:40 UTC, berndverst requested changes
Looks great. Just one important change to be made here on the Get request

 And make sure `dynamoDB` is spelled correctly / consistently throughout :)

2022-03-01 02:40 UTC, berndverst commented on state/aws/dynamodb/dynamodb.go
> +	if result.Item[d.ttlAttributeName] != nil {
Careful, `meta.TTLAttribute` should not be required. So this means the value will be an empty string here. You cannot index into your item with an empty string.

I recommend doing the following:

```suggestion
        if d.ttlAttributeName != "" {
	if val, ok := result.Item[d.ttlAttributeName]; ok {
	   if err = dynamodbattribute.Unmarshal(val, &ttl); err != nil {
```

2022-03-01 02:40 UTC, berndverst commented on state/aws/dynamodb/dynamodb_test.go
> +type DynmoDBItem struct {
```suggestion
type DynamoDBItem struct {
```

2022-03-01 02:43 UTC, berndverst submitted a review, later dismissed
Looks great. Just one important change to be made on the Get request.

Also make sure to spell `dynamodb` variables / structs etc consistently :)

2022-03-03 16:42 UTC, wimvdc commented on state/aws/dynamodb/dynamodb_test.go
> +type DynmoDBItem struct {
Fixed

2022-03-04 16:18 UTC, merged