Support using AAD auth for Event Hubs Storage account
dapr/components-contrib pull request #1578
Opened 2022-03-15 06:02 UTC by berndverst

Signed-off-by: Bernd Verst <4535280+berndverst@users.noreply.github.com>

# Description

Ensures the Event Hubs binding can connect to the Storage Account for leaser / checkpointer using AAD. This requires at least Storage Blob Contributor role at the Storage Account level.

We are reusing the blob storage token from AAD credential auth logic that is well-tested and used elsewhere.

Fixes #1566

2022-03-15 06:02 UTC, berndverst commented
FYI @mukundansundar

2022-03-15 06:16 UTC, mukundansundar commented on pubsub/azure/eventhubs/eventhubs.go
> +	azureEnvironment   *azure.Environment
seems this variable is not used ....

2022-03-15 06:17 UTC, berndverst commented on pubsub/azure/eventhubs/eventhubs.go
> +	azureEnvironment   *azure.Environment
one sec :)

2022-03-15 06:19 UTC, berndverst commented on pubsub/azure/eventhubs/eventhubs.go
> +	azureEnvironment   *azure.Environment
Done!

2022-03-15 06:26 UTC, mukundansundar commented on pubsub/azure/eventhubs/eventhubs.go
> +	azureEnvironment   *azure.Environment
still have the variable.

2022-03-15 06:28 UTC, berndverst commented on pubsub/azure/eventhubs/eventhubs.go
> +	azureEnvironment   *azure.Environment
Pushed the wrong branch. Try now.

2022-03-15 17:33 UTC, surenderssm reviewed
Looks good to me !!

Out of context, I do not see notion of balancing strategy while listening to an event hub. I remember using options like balance and greedy in other SDKs.

2022-03-16 03:16 UTC, daixiang0 requested changes
Could you add tests to cover changes?

2022-03-16 04:52 UTC, berndverst commented
> Could you add tests to cover changes?

This PR is actually a bugfix adding missing behavior to the component. Therefore I would appreciate it if you can approve this @daixiang0.

@mukundansundar tested the component locally previously with AAD authentication but did not update the integration test. He will be creating certification tests to make this component stable. At that point we will be adding the E2E tests.

The alternative IMO is to revert the existing PRs - but that is unnecessary.

2022-03-16 06:51 UTC, daixiang0 approved these changes

2022-03-21 22:06 UTC, merged