Tweaks for ASB pubsub
dapr/components-contrib pull request #1729
Opened 2022-05-17 03:45 UTC by ItalyPaleAle

1. Do not attempt to reconnect when context was canceled
2. Message finalization uses a background context and not the running ctx, in case the app is shutting down

2022-05-17 15:27 UTC, berndverst requested changes
FYI `a.ctx` is currently not receiving context from daprd. None of the pubsub brokers have the context passed through, and this component here sets this to context.background at the moment.

As a result this PR cannot actually have the complete impact (yet).

2022-05-17 15:27 UTC, berndverst commented on pubsub/azure/servicebus/servicebus.go
> +			if a.ctx.Err() != nil {
I think it may be worthwhile to check that this specifically is `context.Canceled` and not DeadlineExceeded or other error contexts.

2022-05-17 16:27 UTC, berndverst commented
> Although the context isn't cascaded from Dapr, this component does use a context internally and it's canceled when the context is closed: https://github.com/dapr/components-contrib/pull/1729/files#diff-8f0a750f05222eb118aded3b8c6c3a926a2564220b5a9c2fd06e6e75c7180aafL615

@ItalyPaleAle but how is the context closed right now?

2022-05-17 16:29 UTC, ItalyPaleAle commented
It's created in the `Init` method

https://github.com/dapr/components-contrib/blob/6b99b02a2d36b69999957e3c790b46a15069e1dc/pubsub/azure/servicebus/servicebus.go#L305

It's closed in the `Close` method, which is invoked by Dapr at shutdown.

https://github.com/dapr/components-contrib/blob/6b99b02a2d36b69999957e3c790b46a15069e1dc/pubsub/azure/servicebus/servicebus.go#L621

Internally in the component, the context is used to cancel subscriptions.

When Dapr adds support for cascading the context, this should work transparently without changes.

2022-05-17 22:12 UTC, ItalyPaleAle commented on pubsub/azure/servicebus/servicebus.go
> -	// Keys.
These defaults were just moved to the `metadata.go` file so they're together with the emtadata keys

2022-05-17 23:01 UTC, ItalyPaleAle commented on bindings/azure/servicebusqueues/servicebusqueues.go
> -func (a *AzureServiceBusQueues) setShutdown() {
These 3 methods are not necessary. We have a context and looking at whether the context has been canceled is thread-safe too.

2022-05-18 05:33 UTC, berndverst approved these changes
Please open Docs PRs to document the new metadata options or any changes to metadata. E.g. `maxRetriablErrorsPerSec`

2022-05-18 05:33 UTC, merged