add mssql binding
dapr/components-contrib pull request #1739
Opened 2022-05-23 06:14 UTC by shakirmengrani

# Description

_Please explain the changes you've made_

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2022-05-23 07:09 UTC, daixiang0 commented
@shakirmengrani thanks for your contribution! Please fix DCO first.

2022-05-23 07:24 UTC, shakirmengrani reviewed
Please review

2022-06-09 14:02 UTC, hueifeng commented
ping?

2022-06-10 21:07 UTC, berndverst commented on bindings/mssql/mssql.go
> +	switch req.Operation {
You didn't implement the exec operation!

Also, when implementing that - please implement it using Prepared Statements. The request should additionally include the arguments to be sent to the prepared statement. See this issue for reference https://github.com/dapr/components-contrib/issues/1699

Given this is a new binding, we should not even allow anything that is not a prepared statement!

2022-06-10 21:09 UTC, berndverst requested changes
Please fix linter issues - there are some bugs here.

Also please implement the `exec` operation, but only to support PreparedStatements (please check the syntax required for MSSQL) or an equivalent secure default.

2022-06-10 21:12 UTC, berndverst commented on bindings/mssql/mssql.go
> +	switch req.Operation {
This example is from Postgres -- not sure if a similar format exists for SQLServer. If it does, we should use prepared statements!

```
{
  "operation": "exec",
  "metadata": {
    "sql": "INSERT INTO foo (id, c1, ts) VALUES ($1, $2, $3)",
    "args": [
        1, 
        'demo', 
        '2020-09-24T11:45:05Z07:00'
    ]
  }
}
```

2022-06-20 16:22 UTC, berndverst commented
Due to lack of response and given the code freeze now I am moving this to release 1.9

2022-07-02 18:18 UTC, closed without merging