middleware: add wasm basic
dapr/components-contrib pull request #1747
Opened 2022-05-24 08:03 UTC by daixiang0

Signed-off-by: Loong <loong.dai@intel.com>

# Description

Basic WASM HTTP middleware implement.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: https://github.com/dapr/components-contrib/issues/1171
## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2022-05-27 04:16 UTC, daixiang0 commented
@shubham1172 could you help check the exact error of fossa? And where is the webapp:
> The build failed. Check the FOSSA webapp for more details.

2022-05-27 04:32 UTC, shubham1172 commented
@daixiang0 you can check out the Dapr project once you login to https://app.fossa.com/projects
As of the build failure, it looks like a FOSSA problem. Scan completed fine; the test step failed without any other information. I don't see anything on the FOSSA portal too. Had created this issue to track https://github.com/fossas/fossa-cli/issues/943

2022-05-31 01:14 UTC, daixiang0 commented
@yaron2 could you take a look?

2022-06-02 03:19 UTC, yaron2 commented
@daixiang0 please resolve the conflict.

2022-06-09 01:18 UTC, yaron2 commented
ping @daixiang0

2022-06-09 01:19 UTC, yaron2 commented
Can you give an example here of how a component YAML would look like for WASM?

2022-06-10 19:55 UTC, berndverst requested changes

2022-06-10 19:55 UTC, berndverst commented on middleware/http/wasm/basic/basic.go
> +func (m *Middleware) getNativeetadata(metadata middleware.Metadata) (*middlewareMetadata, error) {
```suggestion
func (m *Middleware) getNativeMetadata(metadata middleware.Metadata) (*middlewareMetadata, error) {
```

2022-06-10 19:55 UTC, berndverst commented on middleware/http/wasm/basic/basic.go
> +	meta, err = m.getNativeetadata(metadata)
```suggestion
	meta, err = m.getNativeMetadata(metadata)
```

2022-06-10 20:27 UTC, berndverst commented
@yaron2 component should look like this if I'm understanding this PR correctly

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: basicwasm
spec:
  type: middleware.http.wasm.basic
  version: v1
  metadata:
  - name: path
    value: "./hello.wasm"
  - bane: runtime
    value: "wazero"
```

2022-06-13 02:10 UTC, daixiang0 commented
> @yaron2 component should look like this if I'm understanding this PR correctly
> 
> ```
> apiVersion: dapr.io/v1alpha1
> kind: Component
> metadata:
>   name: basicwasm
> spec:
>   type: middleware.http.wasm.basic
>   version: v1
>   metadata:
>   - name: path
>     value: "./hello.wasm"
>   - bane: runtime
>     value: "wazero"
> ```

@berndverst totally correct!

2022-06-13 18:54 UTC, berndverst approved these changes

2022-06-13 19:09 UTC, yaron2 approved these changes

2022-06-13 19:18 UTC, merged

2022-06-28 03:42 UTC, ewassef commented
What is the WASM interface or structure? any guidance here? Also, can this be used with Pub/Sub or just HTTP service invocation?

2023-04-13 09:06 UTC, codefromthecrypt commented
@ewassef sorry about the large delay in responding. I'm just reviewing old issues for the dapr talk at kubecon EU next week.

> What is the WASM interface or structure? any guidance here? Also, can this be used with Pub/Sub or just HTTP service invocation?

Since this PR landed, we had requests to make the model more flexible. We wrote a specification and some SDKs for [http-wasm](https://http-wasm.io/), though currently this is only used by dapr (PR for mosn has been paused due to resources)

So, as of v1.10 this feature is more fleshed out and [documented](https://docs.dapr.io/reference/components-reference/supported-middleware/middleware-wasm/) and has a [sample](https://github.com/dapr/samples/tree/master/hello-wasm), also.

About Pub/Sub, the closest we have in progress now is the output binding, which is incomplete, but I plan to help with this after KubeCon EU next week. It is pure WASI, so there's no pre-defined model (basically you interact via stdin or CLI args). You can subscribe to [this issue](https://github.com/dapr/components-contrib/issues/2274) which I think is prematurely closed as we haven't documented or integrated it into dapr, yet.