[pubsub][rabbitmq]add support for binding multiple routingkeys at the same time
dapr/components-contrib pull request #1750
Opened 2022-05-25 11:44 UTC by saber-wang

# Description

_Please explain the changes you've made_

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #1741

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [√] Code compiles correctly
* [√] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2022-05-31 02:04 UTC, Taction approved these changes
LGTM

2022-06-07 16:02 UTC, yaron2 requested changes

2022-06-07 16:02 UTC, yaron2 commented on pubsub/rabbitmq/rabbitmq.go
> +		r.logger.Infof("%s binding queue '%s' to exchange '%s' with routing key '%s'", logMessagePrefix, q.Name, req.Topic, routingKey)
Can this be a `Debugf` log?

2022-06-10 20:48 UTC, berndverst commented on pubsub/rabbitmq/rabbitmq_test.go
> +	err = pubsubRabbitMQ.Subscribe(pubsub.SubscribeRequest{Topic: topic, Metadata: map[string]string{"routingKey": "keya,keyb,"}}, handler)
```suggestion
	err = pubsubRabbitMQ.Subscribe(context.Background(), pubsub.SubscribeRequest{Topic: topic, Metadata: map[string]string{"routingKey": "keya,keyb,"}}, handler)
```

2022-06-10 20:54 UTC, berndverst approved these changes

2022-06-10 20:55 UTC, berndverst commented
@saber-wang can you please open a Docs PR to clarify this metadata field can be used to specify multiple routingkeys separated by commas?

2022-06-10 20:57 UTC, berndverst approved these changes

2022-06-10 23:34 UTC, merged

2022-06-11 05:36 UTC, saber-wang commented
@berndverst  I updated the docs RP https://github.com/dapr/docs/pull/2465