Certification test for Azure Blob storage state store component
dapr/components-contrib pull request #1896
Opened 2022-07-19 21:21 UTC by tanvigour

Signed-off-by: tanvigour <tanvi.gour@gmail.com>

# Description

_Please explain the changes you've made_

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #1678

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2022-07-19 21:22 UTC, tanvigour commented
@berndverst : I have qualified the non-aad tests locally for this, please review

2022-07-19 21:27 UTC, berndverst commented
> @berndverst : I have qualified the non-aad tests locally for this, please review

Not sure what that means, but we should still include the `masterkey` authentication as a scenario / option here.

2022-07-19 21:29 UTC, tanvigour commented
> > @berndverst : I have qualified the non-aad tests locally for this, please review
> 
> Not sure what that means, but we should still include the `masterkey` authentication as a scenario / option here.



> > @berndverst : I have qualified the non-aad tests locally for this, please review
> 
> Not sure what that means, but we should still include the `masterkey` authentication as a scenario / option here.

i meant, locally i have verified non-aad test qualification, but these changes do have aad authentication scenario as well.

2022-07-19 21:29 UTC, berndverst requested changes
Please add access key authentication. See binding certification test:
https://github.com/dapr/components-contrib/tree/master/tests/certification/bindings/azure/blobstorage

EDIT: Never mind, misunderstood your comment.

2022-07-20 22:03 UTC, berndverst requested changes
Please rebase this PR against the latest master branch and run `make modtidy-all`

2022-07-21 19:36 UTC, berndverst commented on tests/certification/state/azure/blobstorage/README.md
> +2. Able to do set, fetch, delete.
We really do not need to verify these things as this is all handled by conformance test. This just leads to code duplication.

All that needs to be tested is that we can authenticate and do anything.

2022-07-21 19:40 UTC, berndverst approved these changes

2022-07-21 23:24 UTC, berndverst approved these changes

2022-07-21 23:24 UTC, merged