Fix getAll configuration Api for azure app config
dapr/components-contrib pull request #2097
Opened 2022-09-20 12:18 UTC by pravinpushkar

Signed-off-by: Pravin Pushkar <ppushkar@microsoft.com>

# Description

Azure app config getAll used to return older values that are either updated/deleted.
Changed the azure app config sdk API call to get the current values.

## Issue reference

Please reference the issue this PR will close: #2096 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2022-09-20 15:14 UTC, ItalyPaleAle submitted a review, later dismissed

2022-09-22 05:42 UTC, berndverst requested changes

2022-09-22 05:42 UTC, berndverst commented on go.mod
> +	github.com/Azure/azure-sdk-for-go/sdk/data/azappconfig v0.4.1-0.20220914204640-4d445978fe75
We should ask the SDK team to release 0.4.1 or 0.5.0. We should not pin a random commit, only tags.

We still have some time, please reach out to the team.

2022-09-22 05:46 UTC, berndverst commented on go.mod
> +	github.com/Azure/azure-sdk-for-go/sdk/data/azappconfig v0.4.1-0.20220914204640-4d445978fe75
Discussed in team chat - apparently the SDK team suggest using a direct commit in this case.

2022-09-22 06:39 UTC, berndverst approved these changes

2022-09-22 07:04 UTC, merged