Added username and password arguments to pubsub.rabbitmq metadata
dapr/components-contrib pull request #2129
Opened 2022-09-23 21:48 UTC by marioreggiori

# Description

Added `username` and `password` arguments to pubsub.rabbitmq metadata and provide it to `amqp.Dial`.

**Caution:** This is probably a breaking change because the `host` argument was missused to also include credentials.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #1719

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2022-09-23 21:50 UTC, berndverst commented
How about when username and password are empty we fallback to the existing misused behavior to avoid the breaking change?

Could you add that please?

2022-09-23 22:06 UTC, marioreggiori commented
We could omit username and password if the arguments haven't been provided via metadata. Unfortunately this is still a breaking change because we have to prepend the protocol `amqp://`.

2022-09-23 22:45 UTC, marioreggiori commented
Hi @ItalyPaleAle, the idea was to split the connection URI into multiple arguments to support secrets generated by the rabbitmq-operator (containing username and password separately). It appears that referencing other variables with `$(PREVIOUSLY_DEFINED_VAR)` as possible with Kubernetes envs from secrets does not work within dapr `Components`.

2022-09-23 22:50 UTC, marioreggiori commented
> I don't think there is any other protocol (like amqps) :)
Never mind.. I've should have read further :D

2022-09-23 22:50 UTC, berndverst commented
Linter failure

```
  Error: amqp_authority contains underscore. You should use mixedCap or MixedCap. (nosnakecase)
  Error: amqp_authority contains underscore. You should use mixedCap or MixedCap. (nosnakecase)
  Error: amqp_authority contains underscore. You should use mixedCap or MixedCap. (nosnakecase)
```

2022-09-23 22:57 UTC, ItalyPaleAle commented
@marioreggiori here's my proposal:

1. Create a new property "connectionString" which behaves like "host" does today.
1. Keep "host" as it is today and mark it as deprecated. It's an alias of "connectionString", taht will keep working but will not be in docs. If people use that, show a warning in the logs that they should change how they configure the component and use "connectionString" instead. Example of how we do that: https://github.com/dapr/dapr/blob/80f7e4ff9f478275d022cf2d0643028c36d43875/pkg/runtime/runtime.go#L2625-L2626
1. Create a new set of options: "hostname", "username", "password", "protocol". If there's no "connectionString", then construct it from reading from these.

2022-09-23 23:07 UTC, berndverst commented
FYI our code freeze for Dapr 1.9 (when PRs must have been reviewed, reviews sufficiently addressed, and the PR merged) is a week from today.

This PR might not make this next release. The sooner it is completed, the better the chance.

2022-09-23 23:08 UTC, berndverst commented
Please make sure to signoff on all of your commits too -- the DCO check is failing.

2022-09-24 00:04 UTC, marioreggiori commented
@berndverst I'm having difficulties rewording the previous commit which I forgot to sign-off without having to resolve conflicts. Can you please give me a hint on how to solve this?

2022-09-24 00:09 UTC, ItalyPaleAle requested changes
LGTM, just a couple of small comments :)

2022-09-24 00:09 UTC, ItalyPaleAle commented on pubsub/rabbitmq/metadata.go
> +		log.Warn("[DEPRECATION NOTICE] The 'host' argument is deprecated. Use 'connectionString' or individual connection arguments instead.")
Can you add a link to the Dapr docs too in the log messages, which we'll update? https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-rabbitmq/

2022-09-24 00:09 UTC, ItalyPaleAle commented on pubsub/rabbitmq/metadata.go
> +	return fmt.Sprintf("%s://%s", m.protocol, amqpAuthority.String())
I also wonder if we should use `url` to build this, which would also take care of correctly escaping sequences when needed? WDYT?

Something like:

```go
		u := url.URL{}
		u.Scheme = m.protocol
		u.Host = m.hostname
		if m.username != "" {
			u.User = ...
		}
		return u.String()
```

2022-09-24 00:27 UTC, ItalyPaleAle commented
>  I'm having difficulties rewording the previous commit which I forgot to sign-off without having to resolve conflicts. Can you please give me a hint on how to solve this?

Yeah, that's a bit of a pain in the bottom to solve. When I run into those situations, personally what I find easiest is to..... restart from scratch and re-apply the commits.

If you don't care about preserving the previous commits and are ok squashing them:

```sh
git reset --hard upstream/master
curl -L "https://patch-diff.githubusercontent.com/raw/dapr/components-contrib/pull/2129.diff" | git apply
```

Then commit with `git commit -s` as usual.

2022-09-24 02:09 UTC, ItalyPaleAle approved these changes

2022-09-24 02:16 UTC, berndverst approved these changes

2022-09-24 06:37 UTC, merged

2023-02-02 07:18 UTC, shubham1172 commented
@marioreggiori @berndverst this seems to be missing in the docs, is there a docs PR/issue to track this?

2023-02-02 07:24 UTC, berndverst commented
I haven't seen anything. @marioreggiori did you open a PR against the docs repo? We reserve the right to revert any changes that are now documented.

2023-02-02 07:31 UTC, marioreggiori commented
@ItalyPaleAle said that you will take care of the docs. See https://github.com/dapr/components-contrib/pull/2129#discussion_r979124785

> We reserve the right to revert any changes that are not documented.

I currently don't have time to work on this.. So feel free to revert.

2023-02-02 07:33 UTC, shubham1172 commented
Created https://github.com/dapr/docs/issues/3127 to track the docs changes.