Rework JetStream delivery policy
dapr/components-contrib pull request #2315
Opened 2022-11-25 13:34 UTC by Jarema

Signed-off-by: Tomasz Pietrek <tomasz@nats.io>

# Description

_Please explain the changes you've made_

## Issue reference

closes #2314
## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2022-11-25 13:49 UTC, piotrpio requested changes

2022-11-25 13:49 UTC, piotrpio commented on pubsub/jetstream/metadata.go
> +		return metadata{}, fmt.Errorf("deliver policy %s is not one of: all, last, next", deliverPolicy)
```suggestion
		return metadata{}, fmt.Errorf("deliver policy %s is not one of: all, last, new, sequence, time", deliverPolicy)
```

2022-11-29 01:59 UTC, berndverst commented on pubsub/jetstream/metadata.go
> +	"github.com/nats-io/nats.go"
Your imports need to be rearranged.

there need to be 3 blocks of imports in the following order:

- standard library
- other packages
- dapr packages (github.com/dapr)

2022-11-29 02:00 UTC, berndverst requested changes
just fix the import order and then this looks good to me

2022-12-05 16:38 UTC, ItalyPaleAle submitted a review, later dismissed
LGTM

Please also open a PR in the docs repo (https://github.com/dapr/docs/) to document the added/removed metadata options (in the 1.10 branch)

2022-12-14 12:48 UTC, Jarema commented
docs PR added: https://github.com/dapr/docs/pull/3007

2022-12-14 12:59 UTC, piotrpio approved these changes
LGTM

2022-12-14 23:25 UTC, yaron2 approved these changes

2022-12-14 23:56 UTC, merged