Cherry-pick from release into master: Cosmos DB Etag hotfix
dapr/components-contrib pull request #2323
Opened 2022-11-28 23:29 UTC by berndverst

# Description

This is a cherry-pick from release into master of the Cosmos DB Etag hotfix. #2322

2022-11-28 23:54 UTC, ItalyPaleAle approved these changes

2022-11-29 00:00 UTC, artursouza requested changes
Can this be a merge instead?

2022-11-29 00:06 UTC, berndverst commented
@artursouza no because there are commits in release 1.9 that do not belong in master.

2022-11-29 00:07 UTC, merged

2022-11-29 00:08 UTC, artursouza commented
What are those? I don't recall us getting into that situation before.