Add domain and apiPrefix for JetStream
dapr/components-contrib pull request #2400
Opened 2023-01-02 21:06 UTC by Jarema

Signed-off-by: Tomasz Pietrek <tomasz@nats.io>

# Description

Adds ability to setup domain and api prefix for JetStream

## Issue reference

https://github.com/dapr/components-contrib/issues/2265

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2023-01-03 20:03 UTC, berndverst requested changes
Does this introduce new metadata which now are required? Should they be required?

It's a breaking change - which we can do since the component is Alpha, but please do carefully consider whether you need it to be a breaking change.

Also make sure you document these metadata options (I don't see it listed in the metadata section in the 1.10 docs release branch yet)

2023-01-03 20:05 UTC, Jarema commented
This is not a breaking change.
Domain and APIPrefix are both optional.

2023-01-04 08:15 UTC, Jarema commented
@piotrpio please take a look.

2023-01-04 09:50 UTC, Jarema commented
@berndverst I made setup more explicit, so there is no doubt about being breaking or not ;)

2023-01-04 10:01 UTC, piotrpio approved these changes
LGTM

2023-01-04 22:40 UTC, berndverst approved these changes

2023-01-04 22:40 UTC, merged