Apache Pulsar Certification Tests
dapr/components-contrib pull request #2423
Opened 2023-01-09 15:08 UTC by addjuarez

Signed-off-by: addjuarez <6789375+addjuarez@users.noreply.github.com>

# Description

Addition of Apache Pulsar Certification Tests

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

#2013 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2023-01-10 01:35 UTC, berndverst requested changes
Lots of spelling mistakes - take a closer look :)

And fix the `delayqueue` test per my comment. After that I'll take another look.

2023-01-10 01:35 UTC, berndverst commented on tests/certification/pubsub/pulsar/README.md
> +- Verify data with an optional parameter delayqueue set
you are not actually using this parameter anywhere so your current test should not pass.. if it does your test isn't correct

2023-01-10 14:23 UTC, DeepanshuA commented on tests/certification/pubsub/pulsar/docker-compose.yml
> +      - BOOKIE_MEM=" -Xms768m -Xms768m -XX:MaxDirectMemorySize=1g"
```suggestion
      - BOOKIE_MEM=" -Xms768m -Xms768m -XX:MaxDirectMemorySize=1g"
```
- BOOKIE_MEM=" -Xms768m -Xmx768m -XX:MaxDirectMemorySize=1g"

2023-01-10 14:41 UTC, DeepanshuA commented on tests/certification/pubsub/pulsar/pulsar_test.go
> +	subscriberApplication := func(appID string, topicName string, messagesWatcher *watcher.Watcher) app.SetupFn {
`subscriberApplication`, `publishMessages` and `assertMessages` seems to be almost same in all the places - will it be possible to take them out in a separate function?

2023-01-13 01:44 UTC, berndverst requested changes
The `delayqueue` property is still not being used.

2023-01-13 20:31 UTC, addjuarez commented
> The `delayqueue` property is still not being used.

My mistake, delayqueue isnt a property. The properties should be deliverAt and deliverAfter. These are also metadata query parameters and not component properties.

2023-01-20 00:22 UTC, berndverst commented on .github/workflows/certification.yml
> +        - pubsub.mqtt
```suggestion
```

2023-01-20 00:25 UTC, berndverst approved these changes

2023-01-20 00:26 UTC, berndverst commented
@addjuarez  Open docs PR again 1.10 branch to make this component stable.

2023-01-20 16:56 UTC, merged