Fix heartbeat typo
dapr/components-contrib pull request #2430
Opened 2023-01-11 11:20 UTC by Jarema

Signed-off-by: Tomasz Pietrek <tomasz@nats.io>

# Description

_Please explain the changes you've made_

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2023-01-11 11:38 UTC, Jarema commented
Hearbeats were introduced after 1.9, so this should not be a breaking change for released verison AFAIK.

2023-01-11 11:41 UTC, piotrpio approved these changes
LGTM

2023-01-11 21:28 UTC, ItalyPaleAle requested changes

2023-01-11 21:28 UTC, ItalyPaleAle commented on pubsub/jetstream/metadata.go
> +	if v, err := time.ParseDuration(psm.Properties["heartbeat"]); err == nil {
This is a breaking change however. Can you please:

1. Add a fallback logic so if the `hearbeat` property (with typo) is set, but not `heartbeat`, then `hearbeat` is used.
2. Please update the documentation for the component at https://github.com/dapr/docs too

2023-01-11 21:29 UTC, ItalyPaleAle commented
Oh nevermind, I missed the note that heartbeat were not released yet. Then LGTM :) But please, do open an issue in https://github.com/dapr/docs

2023-01-11 21:29 UTC, ItalyPaleAle approved these changes

2023-01-11 22:09 UTC, berndverst approved these changes
I was wondering in the last PR why this said `hearbeat` but then I thought maybe this was a special thing in upstream Jetstream and given you are the authority @Jarema I didn't question it further.

2023-01-12 18:14 UTC, berndverst commented
> Tests seem to be stuck?

Not stuck - just a ton of worker requests pending. It has happened increasingly in contrib.

2023-01-12 19:21 UTC, merged