Add partition support for pulsar
dapr/components-contrib pull request #2647
Opened 2023-03-08 12:28 UTC by bingo1229

# Description

Add Partitioning support for message ordering guarantees of same key.

## Issue reference

Support additional metadata for Apache Pulsar Client Producer option to set Key on the Pulsar Message #2608

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [X] Add partitionKey for publish metadata.
* [X] Add subscribeType, processMode for subscribe metadata.

2023-03-08 22:23 UTC, berndverst commented
Can you write an integration test here (if necessary spinning up docker containers with multiple partitions) to validate that specifying the partition key really works end to end?

Your code has to be added here - https://github.com/dapr/components-contrib/tree/master/tests/certification/pubsub/pulsar

2023-03-10 13:13 UTC, oops-oom commented
> Can you write an integration test here (if necessary spinning up docker containers with multiple partitions) to validate that specifying the partition key really works end to end?
> 
> Your code has to be added here - https://github.com/dapr/components-contrib/tree/master/tests/certification/pubsub/pulsar

@berndverst integration test has been added.

2023-03-13 18:30 UTC, ItalyPaleAle requested changes
Thanks for the PR!! 🙌

2023-03-13 18:30 UTC, ItalyPaleAle commented on pubsub/pulsar/pulsar.go
> +	for name, value := range req.Metadata {
Before the switch, please also add a check to make sure that `value != ""`.

2023-03-13 18:30 UTC, ItalyPaleAle commented on pubsub/pulsar/pulsar.go
> +	for name, value := range req.Metadata {
Something like:

```go
	for name, value := range req.Metadata {
		if value == "" {
			continue
		}

		switch name {
```

2023-03-13 18:30 UTC, ItalyPaleAle commented on pubsub/pulsar/pulsar.go
> +	subsTypeStr, _ := metadata[subscribeTypeKey]
Should we lowercase this?

```suggestion
	subsTypeStr := strings.ToLower(metadata[subscribeTypeKey])
```

2023-03-13 18:30 UTC, ItalyPaleAle commented on pubsub/pulsar/pulsar.go
> +	processModeStr, _ := metadata[processModeKey]
Here too?


```suggestion
	processModeStr := strings.ToLower(metadata[processModeKey])
```

2023-03-13 18:30 UTC, ItalyPaleAle commented on pubsub/pulsar/pulsar.go
> +			if getProcessMode(req) {
I think returning a boolean from this method is not very clear. Perhaps consider something like `if processMode(req) == async`

2023-03-14 16:14 UTC, ItalyPaleAle submitted a review, later dismissed

2023-03-14 16:30 UTC, ItalyPaleAle commented on pubsub/pulsar/pulsar.go
> +			if strings.ToLower(req.Metadata[processModeKey]) == processModeSync {
```suggestion
			if strings.ToLower(req.Metadata[processModeKey]) == processModeSync { //nolint:gocritic
```

2023-03-14 17:01 UTC, merged