rocketmq consumer support some config item
dapr/components-contrib pull request #2811
Opened 2023-04-26 03:21 UTC by naah69

# Description

support the below config item in rocketmq 
```
ConsumeTimestamp
ConsumeConcurrentlyMaxSpan
ConsumeTimeout
ConsumerPullTimeout
PullThresholdForTopic
PullThresholdSizeForQueue
PullThresholdSizeForTopic
```

## Issue reference

Please reference the issue this PR will close: #2756 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2023-04-27 22:59 UTC, berndverst requested changes
Unit tests are failing.

> time="2023-04-27T22:42:33.717240927Z" level=error msg="consumer start failed: the consumer group option validate fail: the specified group[dapr.rocketmq.producer] contains illegal characters, allowing only ^[%|a-zA-Z0-9_-]+$" instance=fv-az621-182 scope=test type=log ver=unknown

Run your tests with `make test` to make sure everything is passing please.

2023-05-01 18:46 UTC, berndverst commented
@naah69 our code freeze will occur any day now - possibly as soon as tomorrow. If the tests in this PR are not passing at that time then unfortunately this PR cannot be included in Dapr 1.11 and you need to wait for Dapr 1.12.

When you work on this PR please run the validations locally to avoid delay in review:
- `make test`
- `make lint`

Update this PR with all changes required to make those two commands pass.

Thanks!

2023-05-04 04:23 UTC, naah69 commented
> @naah69 our code freeze will occur any day now - possibly as soon as tomorrow. If the tests in this PR are not passing at that time then unfortunately this PR cannot be included in Dapr 1.11 and you need to wait for Dapr 1.12.
> 
> When you work on this PR please run the validations locally to avoid delay in review:
> 
> * `make test`
> * `make lint`
> 
> Update this PR with all changes required to make those two commands pass.
> 
> Thanks!

ok,i had fixed it.
please review it.
Thanks

2023-05-04 17:56 UTC, berndverst approved these changes

2023-05-04 17:57 UTC, merged