Adds outbox metadata fields
dapr/components-contrib pull request #3186
Opened 2023-10-20 13:23 UTC by elena-kolevska

# Description
Adds metadata fields needed for the outbox pattern

## Checklist

* [X] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2023-10-21 18:45 UTC, ItalyPaleAle requested changes
Why is this PR targeting release-1.12?

2023-10-21 18:45 UTC, ItalyPaleAle commented on .build-tools/pkg/metadataschema/validators.go
> +					Description: "Sets the topic that receives the state changes on the pub/sub configured with outboxPublishPubsub. The message body will be a state transaction item for an insert or update operati
```suggestion
					Description: `For outbox. Sets the topic that receives the state changes on the pub/sub configured with "outboxPublishPubsub". The message body will be a state transaction item for an insert or update operation`,
```

2023-10-21 18:45 UTC, ItalyPaleAle commented on .build-tools/pkg/metadataschema/validators.go
> +					Description: "Sets the pub/sub component used by Dapr to coordinate the state and pub/sub transactions. If not set, the pub/sub component configured with outboxPublishPubsub is used. This is use
```suggestion
					Description: `For outbox. Sets the pub/sub component used by Dapr to coordinate the state and pub/sub transactions. If not set, the pub/sub component configured with "outboxPublishPubsub" is used. This is useful if you want to separate the pub/sub component used to send the notification state changes from the one used to coordinate the transaction`,
```

2023-10-21 18:45 UTC, ItalyPaleAle commented on .build-tools/pkg/metadataschema/validators.go
> +					Description: "Sets the name of the pub/sub component to deliver the notifications when publishing state changes",
```suggestion
					Description: "For outbox. Sets the name of the pub/sub component to deliver the notifications when publishing state changes",
```

2023-10-21 22:11 UTC, elena-kolevska commented
> Why is this PR targeting release-1.12?

Thanks for the review @ItalyPaleAle. I moved it to `master`.

2023-10-22 00:27 UTC, ItalyPaleAle approved these changes
LGTM thanks!

2023-10-22 00:27 UTC, merged