Azure Blob Storage v2 state store
dapr/components-contrib pull request #3203
Opened 2023-10-31 16:29 UTC by ItalyPaleAle

The v2 of the component does not strip the app's prefix

Fixes #3032

2023-11-01 19:13 UTC, ItalyPaleAle commented on state/azure/blobstorage/v1/metadata.yaml
THere are 2 separate folders for v1 and v2 because there can be only 1 `metadata.yaml` in each folder

2023-11-01 22:51 UTC, berndverst requested changes

2023-11-01 22:51 UTC, berndverst commented on actorstore/postgresql/test-queries.sql
Please remove this file from this PR. Feel free to add in a separate PR. No unrelated change here please.

2023-11-01 23:03 UTC, ItalyPaleAle commented on actorstore/postgresql/test-queries.sql
Oh this was a total accident. Sorry about that! I will remove it

2023-11-01 23:07 UTC, ItalyPaleAle commented on actorstore/postgresql/test-queries.sql
Done

2023-11-02 23:19 UTC, berndverst approved these changes

2023-11-02 23:19 UTC, merged