Add initial OPA middleware certification tests
dapr/components-contrib pull request #3233
Opened 2023-11-17 14:55 UTC by stuartleeks

Signed-off-by: Stuart Leeks <stuartle@microsoft.com>

# Description

Added initial certification tests for OPA HTTP middleware

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [X] Code compiles correctly
* [X] Created/updated tests
* [X] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2024-01-04 17:08 UTC, ItalyPaleAle requested changes
Sorry for the delay! This test looks good to me and I think it's valuable to have.

However, the CI seems to be failing, can you please take a look at that?

Also, the test needs to be enabled in the CI. That is done by adding it to https://github.com/dapr/components-contrib/blob/main/.github/scripts/test-info.mjs

2024-01-05 09:37 UTC, stuartleeks commented
@ItalyPaleAle Thanks - I've added the test and run `make modtidy-all`. Will see whether that has helped the build

2024-01-05 17:45 UTC, ItalyPaleAle commented
> @ItalyPaleAle Thanks - I've added the test and run `make modtidy-all`. Will see whether that has helped the build

Yup, and it works :) https://github.com/dapr/components-contrib/actions/runs/7420243520/job/20205105873?pr=3233

Thanks!

2024-01-05 17:45 UTC, ItalyPaleAle approved these changes

2024-01-05 17:45 UTC, merged