Chore: use a single package for all Feature structs
dapr/components-contrib pull request #3278
Opened 2023-12-18 18:19 UTC by ItalyPaleAle

Also replaces `golang.org/x/exp/slices` with `slices` from the Go 1.21 stdlib

> small spin-off from #3046

2023-12-18 20:44 UTC, berndverst commented
Where is the tracking issue for this? Why are we doing this? I would like some explanation - no PRs without discussion.

2023-12-18 20:44 UTC, berndverst requested changes
Background needed

2023-12-18 22:02 UTC, ItalyPaleAle commented
> Where is the tracking issue for this?

Just a refactoring to avoid code duplication. Instead of having a `Features` struct defined in each package, and the `Contains` method repeated, it's now implemented just once (and re-exported using generics)

2024-01-08 17:06 UTC, berndverst approved these changes

2024-01-08 17:07 UTC, merged