Avro Schema registry consumer implementation
dapr/components-contrib pull request #3292
Opened 2023-12-30 00:53 UTC by passuied

# Description

Add Avro Schema Registry and deserialization to Kafka PubSub Consumer.

## Issue reference

#3144

2023-12-30 02:09 UTC, passuied commented
Please let me know if it's preferable to add publisher in same PR or separate.

2024-01-04 22:45 UTC, yaron2 commented
Great contribution, I really like how this is done and wonder if this approach can be used in the future to enable a generic schema validation feature for all Dapr pub/subs, implemented in the Dapr runtime itself.

For this PR: It'd be best to add a certification test for this functionality (or add this to an existing test).

2024-01-04 23:40 UTC, passuied commented
> For this PR: It'd be best to add a certification test for this functionality (or add this to an existing test).
 Thanks @yaron2, Is there doc about these tests and especially how to run them locally?

2024-01-04 23:52 UTC, ItalyPaleAle commented
The certification tests for Kafka PubSub are here: https://github.com/dapr/components-contrib/tree/main/tests/certification/pubsub/kafka

We don't have good docs (we should....), but for certifications test you just "cd" into the test's folder, and then run `go test -v -tags cerrttests`

2024-01-09 16:19 UTC, yaron2 commented
@passuied please resolve the conflict

2024-01-09 19:15 UTC, ItalyPaleAle requested changes
Thanks for this PR :) left some comments

2024-01-09 19:15 UTC, ItalyPaleAle commented on pubsub/kafka/metadata.yaml
> +      default: '"5min"'
Incorrect format for Go durations:
```suggestion
      example: '"5m"'
      default: '"5m"'
```

2024-01-09 19:15 UTC, ItalyPaleAle commented on bindings/kafka/metadata.yaml
> +    default: '"5min"'
Incorrect format for Go durations:
```suggestion
      example: '"5m"'
      default: '"5m"'
```

2024-01-09 19:15 UTC, ItalyPaleAle commented on common/component/kafka/kafka.go
> +	schemaTypeStr, ok := metadata[valueSchemaType]
Please use this method from dapr/kit which also supports case-insensitive matching: https://github.com/dapr/kit/blob/77f7f031c92afb648d24d6dea18cf80e07fe21d5/metadata/utils.go#L26

2024-01-09 19:15 UTC, ItalyPaleAle commented on common/component/kafka/kafka.go
> +	return fmt.Sprintf("%s-value", topic)
```suggestion
	return topic + "-value"
```

2024-01-09 19:15 UTC, ItalyPaleAle commented on common/component/kafka/kafka.go
> +	if config.ValueSchemaType == Avro {
Nit: please use a switch statement here, it just reads better :) 

Alternatively, change this to be short-circuited, such as :

```go
if config.ValueSchemaType != Avro {
    return message.Value, nil
}
```

2024-01-09 19:15 UTC, ItalyPaleAle commented on common/component/kafka/kafka.go
> +		cacheEntry, ok := k.latestSchemaCache[subject]
This needs a lock around it or it's not safe for concurrent access

2024-01-09 19:15 UTC, ItalyPaleAle commented on common/component/kafka/kafka.go
> +			return nil, nil, err
```suggestion
			return nil, nil, errCodec
```

2024-01-09 19:15 UTC, ItalyPaleAle commented on common/component/kafka/kafka.go
> +		if ok && cacheEntry.expirationTime.Compare(time.Now()) < 0 {
Nit: please use [`time.Before`](https://pkg.go.dev/time#Time.Before) (or `time.After`) for readability

2024-01-09 19:15 UTC, ItalyPaleAle commented on common/component/kafka/kafka.go
> +	if valueSchemaType == Avro {
Nit: please use a switch statement for readability

2024-01-09 19:15 UTC, ItalyPaleAle commented on common/component/kafka/kafka.go
> +		var recordValue []byte
Nit: optimize memory allocation (hopefully I got the right count)

```suggestion
		recordValue := make([]byte, 0, len(schemaIDBytes)+len(valueBytes)+1)
```

2024-01-09 19:15 UTC, ItalyPaleAle commented on common/component/kafka/metadata.go
> +	LatestSchemaCacheTTL    time.Duration `mapstructure:"LatestSchemaCacheTTL"`
I think I'd prefer if this started with "schema" for consistency with the other schema-related properties

```suggestion
	LatestSchemaCacheTTL    time.Duration `mapstructure:"latestSchemaCacheTTL"`
```

2024-01-09 22:36 UTC, passuied commented on common/component/kafka/kafka.go
> +			return nil, nil, err
Thanks! Great catch!

2024-01-10 01:02 UTC, ItalyPaleAle approved these changes

2024-01-10 01:03 UTC, ItalyPaleAle commented
LGTM! @yaron2 good to merge if you are good too

2024-01-10 01:13 UTC, merged

2024-01-10 01:24 UTC, yaron2 commented
Thanks for this @passuied

2024-01-10 01:57 UTC, passuied commented
> Thanks for this @passuied

Thank you for a very smooth PR process ;) That was fun!