FIX: Redis to handle event metadata.
dapr/components-contrib pull request #3320
Opened 2024-01-19 23:46 UTC by artursouza

# Description

_Please explain the changes you've made_

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

RELEASE_NOTE: **FIXED** Redis pubsub now handles event metadata.

2024-01-19 23:48 UTC, artursouza commented on pubsub/redis/redis.go
> +			r.logger.Warnf("Could not extract metadata for Redis message %s: %v", msg.ID, err)
This seems to be better than getting the message stuck because metadata could not be handled.

2024-01-20 00:27 UTC, yaron2 approved these changes

2024-01-20 04:53 UTC, ItalyPaleAle requested changes
Since there's no linked issue, can you please explain what this PR does and why it's needed?

We are past the code freeze phase, so this should probably be merged when the 1.14 merge window opens, unless there's a P0 issue attached to it.

2024-01-20 21:03 UTC, artursouza commented
I can create a specific issue if this needs further discussion. I created two issues that this PR is part of. Basically, bringing having consistency across pubsub components regarding handling of pubsub metadata.

This will only block our integration or E2E tests to reproduce the bug I am fixing for 1.13 - which is a P0 as it makes pubsub unusable for some components with gRPC subscriber.

2024-01-20 21:07 UTC, artursouza commented
> Since there's no linked issue, can you please explain what this PR does and why it's needed?
> 
> We are past the code freeze phase, so this should probably be merged when the 1.14 merge window opens, unless there's a P0 issue attached to it.

See. See the updated description and my comment. This fix can wait until 1.14 but we will not have E2E tests to validate the hotfix for 1.13 - which I can do manually. Of course, we can add yet-another-pubsub to E2E tests, but I don't think it is the right path since this is a basic inconsistency in pubsub that should be fixed (not P0).

2024-01-21 04:41 UTC, ItalyPaleAle commented
@artursouza my .02:

- If this is needed primarily to unblock an E2E test in runtime, I'd prefer if it were added to the in-memory pubsub component for 1.13
- If we agree that all components should support metadata (or at least expose a feature flag for those who do support that or not), then we should have a conformance test to validate this, or the implementation could end up being "patchwork-y"

I'd prefer avoiding adding new features to a "tier 1" component (with a large user base like Redis) when we're already in endgame. But I can be open if other maintainers agree this is the best path forward.

2024-01-21 05:03 UTC, artursouza commented
> @artursouza my .02:
> 
> 
> 
> - If this is needed primarily to unblock an E2E test in runtime, I'd prefer if it were added to the in-memory pubsub component for 1.13
> 
> - If we agree that all components should support metadata (or at least expose a feature flag for those who do support that or not), then we should have a conformance test to validate this, or the implementation could end up being "patchwork-y"
> 
> 
> 
> I'd prefer avoiding adding new features to a "tier 1" component (with a large user base like Redis) when we're already in endgame. But I can be open if other maintainers agree this is the best path forward.

In-memory pubsub does not work for e2e because the subscriber is not the same app as the publisher. While the test can exist with another pubsub, I found it odd for such a basic feature not be supported by all beta and stable pubsub. If this behavior is not standard, then we should add a new column to the feature set of pubsub components. As you see, I opened an issue to discuss the expected behavior for pubsubs and see what others think.

In the worst case, I can add this feature behind a component metadata flag for those that need it.

2024-01-25 01:58 UTC, berndverst commented on pubsub/redis/redis.go
> +func (r *redisStreams) createRedisMessageWrapper(ctx context.Context, stream string, handler pubsub.Handler, msg rediscomponent.RedisXMessage) redisMessageWrapper {
This change is not necessary. It exists the way it is by design because this helper method does not operate on the struct at all. It is static.

2024-01-25 02:02 UTC, berndverst requested changes
I will approve this, but I really think you should add conformance tests.

I will not block on conformance tests, but that is the right thing to do.

My only blocking comment is to please prefix the error message with the component name as I have suggested. This helps with troubleshooting or grepping for similar logs (to see prevalence of an issue etc etc).

Beyond that I am fine merging this.

2024-01-25 02:02 UTC, berndverst commented on pubsub/redis/redis.go
> +func (r *redisStreams) createRedisMessageWrapper(ctx context.Context, stream string, handler pubsub.Handler, msg rediscomponent.RedisXMessage) redisMessageWrapper {
```suggestion
func createRedisMessageWrapper(ctx context.Context, stream string, handler pubsub.Handler, msg rediscomponent.RedisXMessage) redisMessageWrapper {
```

2024-01-25 02:02 UTC, berndverst commented on pubsub/redis/redis.go
> +func (r *redisStreams) createRedisMessageWrapper(ctx context.Context, stream string, handler pubsub.Handler, msg rediscomponent.RedisXMessage) redisMessageWrapper {
Ah, I see you did it because you wanted access to the logger. Ok that's fine then

2024-01-25 04:36 UTC, ItalyPaleAle approved these changes
Given that @berndverst  and @yaron2 both agree to include this, I'm fine too. Thanks for your patience :)

2024-01-25 20:24 UTC, berndverst commented
I took the liberty to apply my suggested log prefix. LGTM now.

2024-01-25 20:24 UTC, berndverst approved these changes

2024-01-25 20:25 UTC, merged