Properly handle serialization deserizliation for redis transaction api.
dapr/components-contrib pull request #460
Opened 2020-09-08 21:06 UTC by mukundansundar

# Description

Found an issue for Transaction API via Java Integration Tests. 

When the state is stored via an **upsert** call made and the got back via the normal getState API call, it can be observed that there is an extra Json Marshal happening in the code. 

Example:
```json
data: "\"{\\\"propertyA\\\":\\\"data in property A\\\",\\\"propertyB\\\":\\\"data in property B\\\"}\""
```
Instead of 
```json
data: "{\"propertyA\":\"data in property A\",\"propertyB\":\"data in property B\"}"
````
The second output is what we have when we have a normal save and get state call done via Dapr. 

The code change here, checks if the incoming request value is a byte array or not and then properly serializes the value. 
## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2020-09-08 21:58 UTC, mukundansundar commented on state/redis/redis.go
> +
changes similar to https://github.com/dapr/components-contrib/pull/460/files#diff-ae10e12c8f4b65b24b405cfe5a7ed386R255

2020-09-12 01:05 UTC, tcnghia commented on state/redis/redis.go
> +			}
```suggestion
			bt, ok := req.Value.([]byte)
			if !ok {
				bt, _ = r.json.Marshal(req.Value)
			}
```

2020-09-14 17:09 UTC, mukundansundar commented on state/azure/cosmosdb/cosmosdb.go
> +			// Value need not be marshaled here. It is handled by cosmosdb client.
https://github.com/a8m/documentdb/blob/59a8c720ee4a28e9aed5fabde2949a85bb3a3238/client.go#L166

2020-09-15 01:44 UTC, youngbupark requested changes

2020-09-15 01:44 UTC, youngbupark commented on state/postgresql/postgresdbaccess.go
> +	var bt []byte
if this code is used in multiple places, it would be great to create shared util.

2020-09-15 17:00 UTC, youngbupark requested changes

2020-09-15 17:23 UTC, youngbupark requested changes

2020-09-15 17:23 UTC, youngbupark commented on state/utils/utils.go
> +	err = nil
no need to set error to nil. in go, default error value is nil.

if you want to set explicitly, 

I would change line 9.
```
var err error = nil
```

2020-09-15 17:49 UTC, artursouza approved these changes

2020-09-15 19:53 UTC, youngbupark approved these changes

2020-09-15 19:54 UTC, merged