Feature/new rabbit bind params
dapr/components-contrib pull request #573
Opened 2021-01-05 22:12 UTC by ianrocha

# Description

_Please explain the changes you've made_

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #572 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2021-01-05 22:27 UTC, yaron2 commented
@ianrocha thanks for this PR, there are conflicts that must be resolved.

2021-01-05 22:28 UTC, yaron2 commented
Make sure you started on a clean branch and that you fetched the latest from master.

2021-01-05 23:01 UTC, yaron2 commented
There's Go linter issues: https://github.com/dapr/components-contrib/pull/573/checks?check_run_id=1653080393

2021-01-06 00:34 UTC, ianrocha commented
Hi @yaron2, sorry for the fails, but can you help my with this one?

https://github.com/dapr/components-contrib/pull/573/checks?check_run_id=1653544208

Do you have any clue about what a could do to solve this?

2021-01-06 00:57 UTC, yaron2 commented
> Hi @yaron2, sorry for the fails, but can you help my with this one?
> 
> https://github.com/dapr/components-contrib/pull/573/checks?check_run_id=1653544208
> 
> Do you have any clue about what a could do to solve this?

Yeah it's just a format issue. For utils/metadata.go, make sure you run go fmt -s utils/metadata.go

2021-01-06 03:04 UTC, ianrocha commented
@yaron2 thanks! it worked great 👍

2021-01-06 03:08 UTC, yaron2 commented
Just to make it clear, this PR adds dead lettering to both the binding AND pubsub?

2021-01-06 03:14 UTC, ianrocha commented
No, the dead lettering arguments are only for the binding. 
The change I made for the pubsub is that now it will receive the parameter exchangeKind, before it could only create an exchange of kind "fanout".

2021-01-06 22:33 UTC, yaron2 commented
> No, the dead lettering arguments are only for the binding.
> The change I made for the pubsub is that now it will receive the parameter exchangeKind, before it could only create an exchange of kind "fanout".

Thanks for clarifying!

Did you perhaps get to test the RabbitMQ pub/sub and bindings after this change? to make sure there are no regressions.

2021-01-07 14:45 UTC, ianrocha commented
It was working good before I merged with master, now I need to test again xD... I think I'll be able to do this on the weekend.

2021-01-11 18:08 UTC, yaron2 commented
hey @ianrocha, please resolve the conflict and we can go ahead and merge this. did you get to test by any chance?

2021-01-11 18:13 UTC, yaron2 approved these changes
LGTM

2021-01-12 22:08 UTC, yaron2 requested changes

2021-01-12 22:08 UTC, yaron2 commented on pubsub/rabbitmq/metadata.go
> +		return &result, fmt.Errorf("%s missing RabbitMQ exchangeKind", errorMessagePrefix)
Please set the exchangeKind here to "fanout" by default

2021-01-12 22:09 UTC, yaron2 commented
@ianrocha I resolved the conflict, left one comment.

2021-01-14 18:45 UTC, yaron2 commented
ping @ianrocha

2021-01-20 18:21 UTC, yaron2 commented
@ianrocha pinging again.

2021-01-25 23:02 UTC, yaron2 commented
Closing as author is non-responsive

2021-01-25 23:02 UTC, closed without merging