no message
dapr/components-contrib pull request #661
Opened 2021-02-06 01:14 UTC by pkedy

# Description

Improving the versatility of the HTTP output binding. Removed the `Read` method since it is not an input binding.

## Issue reference

Related to dapr/docs#153. Will update the docs for this binding as a follow up.

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#153

2021-02-06 01:16 UTC, pkedy commented
Please review @yaron2 @artursouza

2021-02-06 01:18 UTC, mukundansundar reviewed
@pkedy If Read is being removed ... please change to conformance test config too ....

2021-02-08 21:16 UTC, mukundansundar reviewed
@pkedy 
This seems like a breaking change ... it removes HTTP as an input binding.  cc @yaron2 @artursouza 

This also breaks the current conformance tests defined for HTTP binding.

2021-02-08 22:48 UTC, artursouza requested changes

2021-02-08 22:48 UTC, artursouza commented on bindings/http/http.go
> -func (h *HTTPSource) Read(handler func(*bindings.ReadResponse) error) error {
Why removing Read?

2021-02-08 22:55 UTC, yaron2 commented
> @pkedy
> This seems like a breaking change ... it removes HTTP as an input binding. cc @yaron2 @artursouza
> 
> This also breaks the current conformance tests defined for HTTP binding.

@mukundansundar this actually fixes the HTTP binding as it was never meant to be an input binding. the test must change accordingly. /cc @pkedy

2021-02-08 23:09 UTC, artursouza commented
> > @pkedy
> > This seems like a breaking change ... it removes HTTP as an input binding. cc @yaron2 @artursouza
> > This also breaks the current conformance tests defined for HTTP binding.
> 
> @mukundansundar this actually fixes the HTTP binding as it was never meant to be an input binding. the test must change accordingly. /cc @pkedy

Why not?

2021-02-08 23:11 UTC, yaron2 commented
> > > @pkedy
> > > This seems like a breaking change ... it removes HTTP as an input binding. cc @yaron2 @artursouza
> > > This also breaks the current conformance tests defined for HTTP binding.
> > 
> > 
> > @mukundansundar this actually fixes the HTTP binding as it was never meant to be an input binding. the test must change accordingly. /cc @pkedy
> 
> Why not?

In the older implementation, it was an input binding, and input bindings are blocking as they continuously get events. So for the HTTP binding, in practice this meant that the URL defined in the Component was only invoked *once* during startup and never again.

The HTTP binding was really meant to be a bi-directional binding where a user can invoke an external system over HTTP and get the data back.

2021-02-08 23:15 UTC, yaron2 commented on bindings/http/http.go
> -func (h *HTTPSource) Read(handler func(*bindings.ReadResponse) error) error {
See here: https://github.com/dapr/components-contrib/pull/661#issuecomment-775525544

2021-02-08 23:40 UTC, artursouza commented
It can be input binding where it gets dat

> > > > @pkedy
> > > > This seems like a breaking change ... it removes HTTP as an input binding. cc @yaron2 @artursouza
> > > > This also breaks the current conformance tests defined for HTTP binding.
> > > 
> > > 
> > > @mukundansundar this actually fixes the HTTP binding as it was never meant to be an input binding. the test must change accordingly. /cc @pkedy
> > 
> > 
> > Why not?
> 
> In the older implementation, it was an input binding, and input bindings are blocking as they continuously get events. So for the HTTP binding, in practice this meant that the URL defined in the Component was only invoked _once_ during startup and never again.
> 
> The HTTP binding was really meant to be a bi-directional binding where a user can invoke an external system over HTTP and get the data back.

The input binding could trigger an infinite loop getting from the URL every second or so. I am fine removing it for now.

2021-02-08 23:40 UTC, artursouza approved these changes

2021-02-09 20:02 UTC, merged