Tuapuikia
dapr/components-contrib pull request #767
Opened 2021-03-18 19:04 UTC by tuapuikia

# Description

Add option to enable Pulsar exclusive subscription.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2021-03-18 19:23 UTC, tuapuikia commented
@yaron2  Can you help to review my change?

2021-03-19 06:12 UTC, artursouza requested changes

2021-03-19 06:12 UTC, artursouza commented on pubsub/pulsar/metadata.go
> +	Exclusive  string `json:"exclusive"`
Use `bool`, please.

2021-03-19 06:12 UTC, artursouza commented on pubsub/pulsar/pulsar.go
> +	if val, ok := meta.Properties[exclusive]; ok && val != "" {
Please, use the same logic as in enableTLS

2021-03-19 06:12 UTC, artursouza commented on pubsub/pulsar/pulsar.go
> +		p.logger.Debugf("This is exclusive subscription type")
Log this in the beginning of the if statement.

2021-03-19 06:12 UTC, artursouza commented on pubsub/pulsar/pulsar.go
> +		options := pulsar.ConsumerOptions{
The if-else is very similar. It seems that only the type attribute is different, can you handle only the type attribute i if-else and let the common code be deduped?

2021-03-19 07:17 UTC, tuapuikia commented on pubsub/pulsar/metadata.go
> +	Exclusive  string `json:"exclusive"`
OK, let me fix it :+1:

2021-03-22 21:27 UTC, yaron2 commented
ping @tuapuikia

2021-04-21 18:38 UTC, yaron2 commented
@tuapuikia please resolve the conflicts.

2021-08-02 03:11 UTC, tuapuikia commented
Sorry, I was busy with my work. I will resubmit new patch soon.

2021-09-08 03:39 UTC, closed without merging