Add bindings nacos
dapr/components-contrib pull request #814
Opened 2021-04-13 05:05 UTC by cinience

# Description

A binding that allows reading / writing from Nacos Configuration Service.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #810 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2021-04-22 20:41 UTC, pkedy requested changes
Two main changes I'd recommed:

1. Use `config.Decode`
2. Add a component level `ctx context.Context` and implement a `Close() error` func. See the Kafka pubsub as an example. I'll make calling `Close` from dapr/dapr work.

2021-04-22 20:41 UTC, pkedy commented on bindings/alicloud/nacos/nacos.go
> +	if config.dataID == "" || config.group == "" {
Given the `if` above, would `config.group == ""` ever be true?

2021-04-22 20:41 UTC, pkedy commented on bindings/alicloud/nacos/nacos.go
> +	metadata := make(map[string]string, 2)
Simplify to
```golang
metadata := map[string]string{
	metadataConfigID:    dataID,
	metadataConfigGroup: group,
}
```

2021-04-22 20:41 UTC, pkedy commented on bindings/alicloud/nacos/nacos.go
> +	if onchange := req.Metadata[metadataConfigOnchange]; onchange == "true" || onchange == "TRUE" {
Use `strings.EqualFold(onchange, "true")`?

2021-04-22 20:41 UTC, pkedy commented on bindings/alicloud/nacos/nacos.go
> +	exitChan := make(chan os.Signal, 1)
I've seen this in a few components now and its less than ideal but the only way bindings can cleanup at the moment . Just pointing out this issue related to using a `Close() error` method for bindings. #779. I may implement this in `dapr/dapr` so you can use a context for cancelation.

2021-04-22 20:41 UTC, pkedy commented on bindings/alicloud/nacos/nacos.go
> +	if n.watches != nil {
nitpick: You can safely range over a `nil` slice so this check is not needed.

2021-04-22 20:41 UTC, pkedy commented on bindings/alicloud/nacos/nacos_test.go
> +	time.Sleep(time.Second)
Use a channel here?

2021-04-23 23:27 UTC, pkedy commented on bindings/alicloud/nacos/nacos.go
> +	exitChan := make(chan os.Signal, 1)
dapr/dapr#3088 make it so `Close() error` will be called on components. Please use a component level context for cancelation (see the Kafka pubsub for an example)

2021-04-28 21:56 UTC, pkedy requested changes
See my comments re: dapr/dapr#3088.

2021-04-28 21:56 UTC, pkedy commented on bindings/alicloud/nacos/nacos.go
> +			return serverConfigs, fmt.Errorf("%w", err)
Please include a message in `fmt.Errorf`

2021-04-28 21:56 UTC, pkedy commented on bindings/alicloud/nacos/nacos.go
> +	exitChan := make(chan os.Signal, 1)
@cinience dapr/dapr#3088 was merged. Please implement `io.Closer` in this component.

2021-05-04 16:36 UTC, yaron2 commented
ping @pkedy

2021-05-05 20:46 UTC, pkedy commented
@cinience I'm making a small tweaks that moves to of the decoding/validation into the metadata struct (which I renamed Settings). I'd like components to start moving toward this and this will be the first one!

One thing to note for the future is that the `convert` functions could have been implemented using `config.StringDecoder` and decoded directly into naco config types. I didn't want to make those kinds of big changes :)

Only really other thing to note is that I changed the mapstructure name for `TimeoutMs` to `timeout`.

2021-05-05 21:00 UTC, pkedy approved these changes
LGTM but of course did not actually test with nacos middleware. I recommend a follow up PR at somepoint to add an integration test for this.

2021-05-11 22:23 UTC, pkedy approved these changes

2021-05-13 16:48 UTC, pkedy approved these changes

2021-05-13 16:48 UTC, pkedy commented
/cc: @artursouza

2021-05-13 19:06 UTC, artursouza submitted a review, later dismissed

2021-05-13 19:48 UTC, artursouza approved these changes

2021-05-13 19:49 UTC, pkedy approved these changes

2021-05-13 19:53 UTC, merged

2022-09-13 07:10 UTC, tanyo520 commented
When will the Nacos component be merged?