Add redis cluter mode for pubsub
dapr/components-contrib pull request #823
Opened 2021-04-15 16:19 UTC by Taction

# Description

Add redis cluter mode for pubsub, change `*redis.Client` to a `redis.UniversalClient` interface which can be a Client or ClusterClient.Add a `redisType` metadata to define redis type as node or cluster.
There is two different between redis cluster and node.
1. redis cluster's addr option is a string array, which is a string in node. Alough cluster client can find all redis cluster nodes by one redis node, but in case the node is breakdown that the cluster can get cluster nodes info by other nodes. It is better to define addr in cluster mode can include more nodes adderss separated by comma.
2. redis cluster can not define db option for it only use default db0.

## Issue reference

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2021-04-16 23:08 UTC, pkedy approved these changes

2021-04-17 07:31 UTC, Taction commented
I've finish related docs modify and create an issue in doc project

2021-04-21 17:41 UTC, yaron2 requested changes

2021-04-21 17:41 UTC, yaron2 commented on pubsub/redis/redis.go
> +	if val, ok := meta.Properties[redisType]; ok && val != "" {
This is a breaking change to Redis pub/sub. Can you make it so that `redisType` defaults to "node"?

2021-04-21 17:42 UTC, yaron2 approved these changes

2021-04-21 17:42 UTC, yaron2 commented on pubsub/redis/redis.go
> +	if val, ok := meta.Properties[redisType]; ok && val != "" {
Scratch that, missed an else statement :)

2021-04-21 18:33 UTC, merged